#!/usr/bin/env python
from argparse import ArgumentParser
import sys
script_root = "%s/../" % (sys.path[0])
if script_root not in sys.path:
    sys.path.append(script_root)
from qalaunchtime import doQALaunchTime
import adbhelper
